spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

